/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package z;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    private static final Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        log.info("Inicializando backend para a aplicação z...");
        SpringApplication.run(App.class, args);
    }
}
